tail_format_prompt_point = [
    # Original formats
    ("(with point).", "({},{})"),
    
    ("return the coordinates of the element in the format of (x,y).", "({},{})"),
    ("your answer should be in json format with key 'point'.", "{{'point': ({},{})}}"),
    ("answer the question with given format: {'x': x, 'y': y}.", "{{'x': {}, 'y': {}}}"),
    ("provide the position as [x,y].", "[{},{}]"),
    ("respond with coordinates formatted as x:number,y:number.", "x:{},y:{}"),
    ("return the location using format: coordinate(x,y).", "coordinate({},{})"),
    ("specify the exact position using (horizontal,vertical) notation.", "({},{})"),
    ("reply with position data in this format: {coordinates:[x,y]}.", "{{coordinates:[{},{}]}}"),
    ("respond with click_position=(x_value,y_value).", "click_position=({},{})"),
    ("return location data as 'position_x: number, position_y: number'.", "position_x: {}, position_y: {}"),
    ("provide element coordinates using the format |x,y|.", "|{},{}|"),
    ("respond with {\"target\": {\"horizontal\": x, \"vertical\": y}}.", "{{\"target\": {{\"horizontal\": {}, \"vertical\": {}}}}}"),
    ("return the pixel position as 'pixel(x=number,y=number)'.", "pixel(x={},y={})"),
    ("specify the target with format 'element_location=[x_coord,y_coord]'.", "element_location=[{},{}]"),
    ("provide exact location using format: Point X=number Y=number.", "Point X={} Y={}"),
    ("return a tuple representing (x-coordinate, y-coordinate).", "({}, {})"),
    ("respond with coordinates in the format {\"click_at\": [x, y]}.", "{{\"click_at\": [{}, {}]}}"),
    ("provide the exact location as '<position x=\"number\" y=\"number\"/>'.", "<position x=\"{}\" y=\"{}\"/>"),
    ("return element position formatted as 'at_position(x, y)'.", "at_position({}, {})"),
    ("answer with the coordinates in the format {loc: {x: number, y: number}}.", "{{loc: {{x: {}, y: {}}}}}"),
    ("provide mouse click position as 'mouse_position(column=number, row=number)'.", "mouse_position(column={}, row={})")
]

tail_format_prompt_bbox = [
    # Your existing formats
    ("(with bbox).", "({},{},{},{})"),
    ("return the coordinates of the element in the format of (x1,y1,x2,y2).", "({},{},{},{})"),
    ("your answer should be in json format with key 'bbox'.", "{{'bbox': ({},{},{},{})}}"),
    ("answer the question with given format: {'x1': x1, 'y1': y1, 'x2': x2, 'y2': y2}.", "{{'x1': {}, 'y1': {}, 'x2': {}, 'y2': {}}}"),
    
    # New formats
    ("provide the bounding box coordinates as [x1,y1,x2,y2].", "[{},{},{},{}]"),
    ("return element location as (top-left x, top-left y, bottom-right x, bottom-right y).", "({},{},{},{})"),
    ("specify the element position using coordinates (minX,minY,maxX,maxY).", "({},{},{},{})"),
    ("respond with a dict containing coordinates {'x_min': x1, 'y_min': y1, 'x_max': x2, 'y_max': y2}.", "{{'x_min': {}, 'y_min': {}, 'x_max': {}, 'y_max': {}}}"),
    ("output the bounding box using the format: left={},top={},right={},bottom={}.", "left={},top={},right={},bottom={}"),
    ("return a JSON object with the format: {'coordinates': [{}, {}, {}, {}]}.", "{{'coordinates': [{}, {}, {}, {}]}}"),
    ("the element position should be given as a list in the order [left, top, right, bottom].", "[{}, {}, {}, {}]"),
    ("provide the element's boundary as {'left': x1, 'top': y1, 'right': x2, 'bottom': y2}.", "{{'left': {}, 'top': {}, 'right': {}, 'bottom': {}}}"),
    ("return the position as start_x={}, start_y={}, end_x={}, end_y={}.", "start_x={}, start_y={}, end_x={}, end_y={}"),
    ("output the box dimensions in the form (x_start,y_start,x_end,y_end).", "({},{},{},{})"),
    ("specify the bounding region as {'startPoint': [{}, {}], 'endPoint': [{}, {}]}. ", "{{'startPoint': [{}, {}], 'endPoint': [{}, {}]}}"),
    ("provide the element location as corner_tl=({},{}) corner_br=({},{}).", "corner_tl=({},{}) corner_br=({},{})"),
    ("respond with a tuple of coordinates in pixels: pixels(x1,y1,x2,y2).", "pixels({},{},{},{})"),
    ("output the element boundaries as location=(x1,y1,x2,y2).", "location=({},{},{},{})"),
    ("return the region as {'topLeft': [{}, {}], 'bottomRight': [{}, {}]}. ", "{{'topLeft': [{}, {}], 'bottomRight': [{}, {}]}}"),
    ("provide the element's boundary box as rect({}, {}, {}, {}).", "rect({}, {}, {}, {})"),
]



web_loca_all_prompt_prefix = [
    "In the screenshot of this web page, ",
    "Based on the screenshot of the page, ",
    "In the image above, ",
    "In the screenshot, ",
    "Please identify from the screenshot ",
    "Given a screenshot, ",
    "Using the image of this webpage, ",
    "In this webpage capture, ",
    "From this webpage screenshot, ",
    "From the given webpage screenshot, ",
    "Based on this screenshot, ",
    "For this page capture, ",
    "From this webpage screenshot, ",
    "Using the attached screenshot of a webpage, ",
    "From the image of this webpage, ",
    "In this webpage screenshot, ",
    "On this webpage screenshot, ",
    "In this web page image, ",
    "Given this screenshot of a webpage, ",
    "Using the provided webpage screenshot, ",
    "In the provided web page image, ",
    "With this screenshot of a webpage, ",
    "In this webpage screenshot, ",
    "Using the screenshot of this webpage, ",
    "On this webpage capture, ",
    "In this webpage screenshot, ",
    "In this webpage image, ",
    "Using this webpage screenshot, ",
    "Based on this webpage screenshot, ",
    "In this web page capture, ",
    "In this webpage screenshot, ",
    "Using the provided screenshot, ",
    "From this webpage image, "
]

web_loca_all_bbox_prompt = [
    "please give me the coordinates of the element I want to click on according to my instructions",
    "I give a text description and you give its corresponding location",
    "I will give a series of descriptions of the elements to be clicked. Please predict where you want to click",
    "I will give textual descriptions of certain elements. Please predict the location of the corresponding element",
    "the coordinates of the webpage elements I describe",
    "I will describe specific elements; your task is to predict their locations",
    "can you determine the coordinates of the elements I describe?",
    "I will describe certain elements. Please locate them for me",
    "I'll provide textual descriptions of elements. Can you find their coordinates?",
    "I need you to identify the locations of described elements",
    "I'll describe some elements. Please pinpoint their exact locations",
    "can you predict their positions for the elements I describe?",
    "I will describe elements; your role is to locate them",
    "please find the coordinates of described elements",
    "I will describe elements for you to locate",
    "I'll give descriptions of certain elements; please identify where they are",
    "I will point out elements; please predict their exact coordinates",
    "please locate the elements as I describe them",
    "I'll describe some elements; locate them for me",
    "locate the elements I describe",
    "I'll describe specific elements. Identify their locations, please",
    "can you locate the elements I describe?",
    "I will describe features; please predict their positions",
    "identify the coordinates of elements I describe",
    "I'll point out specific elements for you to locate",
    "determine the location of elements I describe",
    "I'll describe certain elements; your task is to find their locations",
    "I'll describe some elements. Please locate them",
    "find the locations of elements I describe",
    "please predict the positions of elements I describe",
    "I'll give textual clues about elements; identify their coordinates",
    "I'll describe elements for you to locate",
    "I will describe specific elements. Please predict their exact locations"
]



# locate all elements in a webpage (point)
web_loca_all_point_prompt = [
    "please give me the coordinates of the element I want to click on according to my instructions",
    "I give a text description and you give its corresponding location",
    "I will give a series of descriptions of the elements to be clicked. Please predict where you want to click",
    "I will give textual descriptions of certain elements. Please predict the location of the corresponding element",
    "the coordinates of the webpage elements I describe",
    "I will describe specific elements; your task is to predict their locations",
    "can you determine the coordinates of the elements I describe?",
    "I will describe certain elements. Please locate them for me",
    "I'll provide textual descriptions of elements. Can you find their coordinates?",
    "I need you to identify the locations of described elements",
    "I'll describe some elements. Please pinpoint their exact locations",
    "can you predict their positions for the elements I describe?",
    "I will describe elements; your role is to locate them",
    "please find the coordinates of described elements",
    "I will describe elements for you to locate",
    "I'll give descriptions of certain elements; please identify where they are",
    "I will point out elements; please predict their exact coordinates",
    "please locate the elements as I describe them",
    "I'll describe some elements; locate them for me",
    "locate the elements I describe",
    "I'll describe specific elements. Identify their locations, please",
    "can you locate the elements I describe?",
    "I will describe features; please predict their positions",
    "identify the coordinates of elements I describe",
    "I'll point out specific elements for you to locate",
    "determine the location of elements I describe",
    "I'll describe certain elements; your task is to find their locations",
    "I'll describe some elements. Please locate them",
    "find the locations of elements I describe",
    "please predict the positions of elements I describe",
    "I'll give textual clues about elements; identify their coordinates",
    "I'll describe elements for you to locate",
    "I will describe specific elements. Please predict their exact locations"
]



# UI location prefixes
ui_loca_prompt_prefix = [
    "In this UI screenshot, ",
    "In the UI, ",
    "In this screen, ",
    "On this page, ",
    "For the action described as \"{}\", ",
    "To execute the function \"{}\", ",
    "In this UI layout, ",
    "On this screen, ",
    "In the software interface, ",
    "Within this dashboard, ",
    "In the UI here, ",
    "If my goal is to \"{}\", ",
    "On this device screen, ",
    "Facing this interface, ",
    "In this digital interface, ",
    "When using this app, ",
    "In this UI design, ",
    "Within this graphical user interface, ",
    "On this web page, ",
    "In this interface snapshot, ",
    "When interacting with this UI, ",
    "On this software's interface, ",
    "In the current UI, ",
    "In this image, ",
    "In the current UI, ",
    "In this image, ",
    "On this screen, ",
    "In the UI right now, ",
    "In this layout, ",
    "On this interface, ",
    "In this view, ",
    "On this page, ",
    "In this webpage, ",
    "In this software, "
]

# locate screen element（bbox)
loca_bbox_prompt = [
    "what is the position of the element corresponding to the command \"{}\"?",
    "where should I click if I want to complete instruction \"{}\"?",
    "how can I navigate to the section that says \"{}\"?",
    "what is the location of the button do I press to follow the command \"{}\"?",
    "where is the corresponding icon?",
    "which item in the UI should I select (in coordinates)?",
    "where is the tool that performs the operation \"{}\"?",
    "where can I find the feature that allows me to \"{}\"?",
    "which menu item corresponds to the task \"{}\" (in coordinates)?",
    "which widget should I interact with to \"{}\"?",
    "I need to {}, what is the coordinates of the element is related to this?",
    "which control in this interface should I use?",
    "to achieve the outcome \"{}\", where do I tap?",
    "where do I access to \"{}\"?",
    "to initiate \"{}\", where is my point of interest?",
    "for the function \"{}\", where is the command located?",
    "to process the instruction \"{}\", where should I activate?",
    "to \"{}\", which icon should I be looking for?",
    "to perform \"{}\", where is the link or button I will click?",
    "to begin \"{}\", what is the clicking point?",
    "for the operation labeled \"{}\", what is my target?",
    "to execute the step \"{}\", where do I direct my attention?",
    "I want to {}, where should I click?",
    "I want to {}, where should I click on?",
    "to {}, where should I click?",
    "to {}, where should I click on?",
    "I need to {}, where do I click?",
    "to {}, where should I click?",
    "I want to {}, where is the upload button?",
    "to {}, where should I click?",
    "I need to {}, which icon do I select (in coordinates)?",
    "I want to {}, where is the option?",
    "I'm trying to {}, where do I click?",
    "to {}, where should I navigate?"
]

# locate screen element（point)
loca_point_prompt = [
    "what is the position of the element corresponding to the command \"{}\"?",
    "where should I click if I want to complete instruction \"{}\"?",
    "how can I navigate to the section that says \"{}\"?",
    "what is the location of the button do I press to follow the command \"{}\"?",
    "where is the corresponding icon?",
    "which item in the UI should I select (in coordinates)?",
    "where is the tool that performs the operation \"{}\"?",
    "where can I find the feature that allows me to \"{}\"?",
    "which menu item corresponds to the task \"{}\" (in coordinates)?",
    "which widget should I interact with to \"{}\"?",
    "I need to {}, what is the coordinates of the element is related to this?",
    "which control in this interface should I use?",
    "to achieve the outcome \"{}\", where do I tap?",
    "where do I access to \"{}\"?",
    "to initiate \"{}\", where is my point of interest?",
    "for the function \"{}\", where is the command located?",
    "to process the instruction \"{}\", where should I activate?",
    "to \"{}\", which icon should I be looking for?",
    "to perform \"{}\", where is the link or button I will click?",
    "to begin \"{}\", what is the clicking point?",
    "for the operation labeled \"{}\", what is my target?",
    "to execute the step \"{}\", where do I direct my attention?",
    "I want to {}, where should I click?",
    "I want to {}, where should I click on?",
    "to {}, where should I click?",
    "to {}, where should I click on?",
    "I need to {}, where do I click?",
    "to {}, where should I click?",
    "I want to {}, where is the upload button?",
    "to {}, where should I click?",
    "I need to {}, which icon do I select (in coordinates)?",
    "I want to {}, where is the option?",
    "I'm trying to {}, where do I click?",
    "to {}, where should I navigate?"
]

# screen caption
screen_caption_prompt = [
    "Can you provide a detailed description of the interface screenshot shown?",
    "Illustrate the details visible in the provided screenshot.",
    "What does the presented screen image depict?",
    "How would you narrate the contents of this screen capture to someone who can't see it?",
    "Please detail the elements shown in the interface screenshot.",
    "Describe the features and information displayed in this screenshot.",
    "Elaborate on what is visible in the screenshot of the interface.",
    "Give a comprehensive description of the screenshot's interface.",
    "What information is conveyed in the screenshot displayed?",
    "Could you depict the content and layout of the screen image provided?",
    "Explain the visual aspects of the screenshot taken from this interface.",
    "How would you verbally depict the interface shown in the screenshot?",
    "What key elements are shown in this interface screenshot?",
    "Provide a verbal representation of the screenshot's content.",
    "Narrate the components and information visible in this interface capture.",
    "What are the main features displayed in the screenshot of this screen?",
    "Outline the specific details shown in the interface image.",
    "How would you describe this screen image to someone who cannot see it?",
    "Enumerate the elements and information present in the provided interface screenshot.",
    "Detail the visual composition of the screen capture you see."
]

# widget captioning
widgetcap_prompt = [
    "Please generate a description for the element at {}.",
    "Describe the function of the element at {} on the screen.",
    "What is the function of the element at {} on the UI?",
    "What happens when you tap position {} on the screen?",
    "What happens when you click point {} on the screen?",
    "Can you explain what the user interface element at {} does?",
    "What action is triggered by interacting with the area at {}?",
    "Explain the purpose of the interactive element found at {}.",
    "What feature is accessed by selecting the location at {}?",
    "Identify and describe the component located at {}.",
    "What is the outcome of selecting the element at {}?",
    "Detail the functionality of the UI element positioned at {}.",
    "What is the significance of the element located at {} in the application?",
    "How does the element at {} contribute to the overall user experience?",
    "What kind of input or interaction is expected at the point marked {}?"
]

# ocr all elements in a webpage (bbox)
web_ocr_all_bbox_prompt = [
    "Based on the screenshot of the web page, I give you the location to click on and you predict the text content of the corresponding element (with bbox).",
    "In the image above, I give a series of coordinates and ask you to describe the corresponding elements (with bbox).",
    "On this page, I will give you a series of coordinates and ask you to predict the text of the clickable element that corresponds to these coordinates (with bbox).",
    "Given a webpage screenshot, I provide coordinates; predict the text content of the elements at these locations (with bbox).",
    "In this screenshot, I'll give coordinates and ask you to describe the text of the elements there (with bbox).",
    "Using the provided image of the webpage, I'll specify locations; you predict the text content of those elements (with bbox).",
    "With this webpage capture, I provide a series of coordinates; please identify the text content of each element (with bbox).",
    "In this page image, I'll point to specific locations; you need to predict the text of the corresponding elements (with bbox).",
    "From this screenshot, I'll give coordinates; can you describe the text of the elements at these points (with bbox)?",
    "Based on this web page screenshot, I provide coordinates; please predict the textual content at these spots (with bbox).",
    "Using the given image of the webpage, I'll specify certain coordinates; describe the text of the elements there (with bbox).",
    "On this captured webpage, I will give a series of coordinates; your task is to predict the text at these locations (with bbox).",
    "With this webpage image, I provide coordinates; can you tell me the text of the elements at these points (with bbox)?",
    "In the provided webpage screenshot, I'll point out locations; please describe the text of the elements there (with bbox).",
    "From this web page capture, I give specific coordinates; predict the text content of the elements at these locations (with bbox).",
    "Using this screenshot of a webpage, I'll indicate coordinates; can you predict the text of the elements (with bbox)?",
    "On this image of a web page, I provide coordinates; you need to describe the text of the corresponding elements (with bbox).",
    "Given this webpage capture, I'll specify locations; please predict the text content of the elements there (with bbox).",
    "In this screenshot, I give a series of coordinates; your task is to predict the text content of the elements (with bbox).",
    "From the given webpage image, I'll provide coordinates; can you describe the text of the elements at these points (with bbox)?",
    "On this captured webpage, I provide specific coordinates; you need to predict the text of the elements there (with bbox).",
    "Using this web page screenshot, I'll indicate locations; please describe the text content of the elements (with bbox).",
    "With this image of a webpage, I specify coordinates; your task is to predict the text of the corresponding elements (with bbox).",
    "In this webpage capture, I'll give coordinates; can you predict the text content of the elements at these locations (with bbox)?",
    "Based on this screenshot, I provide a series of coordinates; describe the text of the elements there (with bbox).",
    "Using the image of this webpage, I'll specify locations; you need to predict the text of the elements (with bbox).",
    "On this page screenshot, I give coordinates; please predict the text content of the corresponding elements (with bbox).",
    "From this webpage image, I'll indicate specific coordinates; can you describe the text of the elements (with bbox)?",
    "In this web page image, I provide coordinates; your task is to predict the text of the elements at these locations (with bbox).",
    "Given this screenshot of a webpage, I specify locations; please describe the text of the elements there (with bbox).",
    "Using the provided page image, I'll point to locations; you predict the text content of the elements (with bbox).",
    "On this webpage capture, I provide a series of coordinates; can you predict the text of the elements (with bbox)?",
    "With this image of the web page, I give specific coordinates; your task is to describe the text of the elements at these points (with bbox)."
]

# ocr all elements in a webpage (point)
web_ocr_all_point_prompt = [
    "Based on the screenshot of the web page, I give you the location to click on and you predict the text content of the corresponding element (with point).",
    "In the image above, I give a series of coordinates and ask you to describe the corresponding elements (with point).",
    "On this page, I will give you a series of coordinates and ask you to predict the text of the clickable element that corresponds to these coordinates (with point).",
    "Given a webpage screenshot, I provide coordinates; predict the text content of the elements at these locations (with point).",
    "In this screenshot, I'll give coordinates and ask you to describe the text of the elements there (with point).",
    "Using the provided image of the webpage, I'll specify locations; you predict the text content of those elements (with point).",
    "With this webpage capture, I provide a series of coordinates; please identify the text content of each element (with point).",
    "In this page image, I'll point to specific locations; you need to predict the text of the corresponding elements (with point).",
    "From this screenshot, I'll give coordinates; can you describe the text of the elements at these points (with point)?",
    "Based on this web page screenshot, I provide coordinates; please predict the textual content at these spots (with point).",
    "Using the given image of the webpage, I'll specify certain coordinates; describe the text of the elements there (with point).",
    "On this captured webpage, I will give a series of coordinates; your task is to predict the text at these locations (with point).",
    "With this webpage image, I provide coordinates; can you tell me the text of the elements at these points (with point)?",
    "In the provided webpage screenshot, I'll point out locations; please describe the text of the elements there (with point).",
    "From this web page capture, I give specific coordinates; predict the text content of the elements at these locations (with point).",
    "Using this screenshot of a webpage, I'll indicate coordinates; can you predict the text of the elements (with point)?",
    "On this image of a web page, I provide coordinates; you need to describe the text of the corresponding elements (with point).",
    "Given this webpage capture, I'll specify locations; please predict the text content of the elements there (with point).",
    "In this screenshot, I give a series of coordinates; your task is to predict the text content of the elements (with point).",
    "From the given webpage image, I'll provide coordinates; can you describe the text of the elements at these points (with point)?",
    "On this captured webpage, I provide specific coordinates; you need to predict the text of the elements there (with point).",
    "Using this web page screenshot, I'll indicate locations; please describe the text content of the elements (with point).",
    "With this image of a webpage, I specify coordinates; your task is to predict the text of the corresponding elements (with point).",
    "In this webpage capture, I'll give coordinates; can you predict the text content of the elements at these locations (with point)?",
    "Based on this screenshot, I provide a series of coordinates; describe the text of the elements there (with point).",
    "Using the image of this webpage, I'll specify locations; you need to predict the text of the elements (with point).",
    "On this page screenshot, I give coordinates; please predict the text content of the corresponding elements (with point).",
    "From this webpage image, I'll indicate specific coordinates; can you describe the text of the elements (with point)?",
    "In this web page image, I provide coordinates; your task is to predict the text of the elements at these locations (with point).",
    "Given this screenshot of a webpage, I specify locations; please describe the text of the elements there (with point).",
    "Using the provided page image, I'll point to locations; you predict the text content of the elements (with point).",
    "On this webpage capture, I provide a series of coordinates; can you predict the text of the elements (with point)?",
    "With this image of the web page, I give specific coordinates; your task is to describe the text of the elements at these points (with point)."
]